repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(src)
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
    types_or: [c++, c]
- repo: local
  hooks:
    - id: cppcheck
      name: cppcheck
      entry: cppcheck
      language: system
      types_or: [c++, c]
      args: ["--error-exitcode=0"]
    - id: cpplint
      name: cpplint
      entry: cpplint
      language: system
      types_or: [c++, c]
      args: ["--filter=-whitespace/comments,-runtime/references,-whitespace/indent,-runtime/int,-build/c++11"]
    - id: meson-format
      name: meson format
      entry: meson
      language: system
      types: [meson]
      files: \.build$
      args: ["format", "-i"]
