name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.8-0'
        environment-file: environment.yml
        init-shell: >-
          bash
          powershell
        cache-environment: true
        post-cleanup: 'all'
    - name: Run precommit
      shell: bash -l {0}
      run: |
        pipx run pre-commit run -a
