name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install environment
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: 'v0.32.0'
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    - name: Run precommit
      shell: pixi run bash -e {0}
      run: |
        pipx run pre-commit run -a
